import Vue from 'vue'
// the component
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
// the library
import { config, library } from '@fortawesome/fontawesome-svg-core'
// manual
config.autoAddCss = false

// fab
import {
  faTwitter,
  faFacebookF,
  faTwitterSquare,
  faLine,
  faFacebookSquare,
  faFacebook,
  faYoutube,
  faInstagram,
  faTripadvisor,
  faAppStoreIos,
  faGooglePlay
} from '@fortawesome/free-brands-svg-icons'
// fas
import {
  faCaretDown,
  faBookmark,
  faSearch,
  faChevronDoubleRight,
  faDotCircle,
  faCommentAltEdit,
  faPlus,
  faBallotCheck,
  faUser,
  faWifi,
  faSyncAlt,
  faChalkboardTeacher,
  faUserEdit,
  faFire,
  faTimes,
  faArrowAltCircleRight,
  faAngleUp,
  faBars,
  faCircle,
  faPepperHot,
  faUndoAlt,
  faHospitalUser,
  faPaw,
  faSubway,
  faBus,
  faTaxi,
  faPhone,
  faTrain,
  faBrowser,
  faPray,
  faChevronCircleRight,
  faChevronRight,
  faPalletAlt,
  faChevronLeft,
  faUsersClass,
  faShareAlt,
  faHome,
  faMobileAlt,
  faExternalLink,
  faExternalLinkAlt,
  faTags,
  faHeadset,
  faQuoteLeft,
  faCaretRight,
  faHandsHelping,
  faScrubber,
  faStars,
  faShoppingCart,
  faSoup,
  faUtensils,
  faQuoteRight,
  faWarehouseAlt,
  faMapMarkerAlt as fasFaMapMarkerAlt
} from '@fortawesome/pro-solid-svg-icons'
// fal
import {
  faLockAlt,
  faTrophy,
  faChevronDoubleDown,
  faLongArrowAltRight,
  faLongArrowAltDown,
  faAngleUp as falFaAngleUp,
  faAngleRight,
  faAngleDown,
  faAngleLeft,
  faHandsHeart,
  faHospitalAlt,
  faIdCard,
  faUserNurse,
  faUserHeadset,
  faUsersMedical,
  faBacon,
  faSalad,
  faClipboardCheck,
  faClipboardList,
  faUserMdChat,
  faUserTie,
  faUsers,
  faUserCircle,
  faNotesMedical,
  faFileMedical,
  faCar,
  faCalculator,
  faWalking,
  faPlaneAlt,
  faFax,
  faStamp,
  faBullhorn,
  faPeopleCarry,
  faBullseyeArrow,
  faGraduationCap,
  faCommentAltSmile,
  faTshirt,
  faToothbrush,
  faShower,
  faShoePrints,
  faExternalLinkSquareAlt,
  faBoothCurtain,
  faPhone as falPhone,
  faSubway as falSubway,
  faTrain as falTrain,
  faLongArrowRight,
  faLongArrowDown,
} from '@fortawesome/pro-light-svg-icons'
// far
import {
  faExternalLink as farExternalLink,
  faMapMarkerAlt,
  faTimesCircle,
  faMobileAndroid,
  faClock,
  faPlay,
  faBed,
  faBell,
  faUserMd,
  faFilePdf,
  faGlobe,
  faSmile,
  faTv,
  faToilet,
  faStore,
  faPlayCircle
} from '@fortawesome/pro-regular-svg-icons'

library.add(
  faBed,
  faStars,
  faTimes,
  faTimesCircle,
  faBookmark,
  faChevronDoubleRight,
  faWifi,
  faChevronDoubleDown,
  faClipboardCheck,
  faClipboardList,
  faBrowser,
  faPlay,
  faShoppingCart,
  faCircle,
  faCalculator,
  faChevronCircleRight,
  faCommentAltSmile,
  faDotCircle,
  faStamp,
  faIdCard,
  faAppStoreIos,
  faGooglePlay,
  faTwitter,
  faFacebookF,
  faFileMedical,
  faTwitterSquare,
  faSyncAlt,
  faLine,
  faFacebookSquare,
  faFacebook,
  faBell,
  faFilePdf,
  faGlobe,
  faUserTie,
  faYoutube,
  faInstagram,
  faMobileAndroid,
  faCaretDown,
  faFire,
  faArrowAltCircleRight,
  faAngleUp,
  faAngleRight,
  faAngleLeft,
  faAngleDown,
  faBacon,
  faPhone,
  falPhone,
  faPlayCircle,
  faUsersMedical,
  faUserNurse,
  faUndoAlt,
  faUsersClass,
  faMapMarkerAlt,
  faSubway,
  faBus,
  faTaxi,
  faTrain,
  faPepperHot,
  faPray,
  faPalletAlt,
  faPeopleCarry,
  faPaw,
  faChevronRight,
  faChevronLeft,
  faShareAlt,
  faLongArrowAltRight,
  faLongArrowAltDown,
  falFaAngleUp,
  faHome,
  faMobileAlt,
  faExternalLink,
  faExternalLinkAlt,
  faHeadset,
  faNotesMedical,
  faTv,
  faLockAlt,
  faPlus,
  faSearch,
  faBars,
  faTrophy,
  faTags,
  faToilet,
  faClock,
  faCaretRight,
  faHandsHeart,
  faHandsHelping,
  faUserEdit,
  faHospitalAlt,
  faIdCard,
  faSalad,
  faSmile,
  faHospitalUser,
  faUserMdChat,
  faUserMd,
  faUserHeadset,
  faUser,
  faUsers,
  faUserCircle,
  faCommentAltEdit,
  faChalkboardTeacher,
  faScrubber,
  faQuoteLeft,
  faQuoteRight,
  faCar,
  faTripadvisor,
  faWalking,
  faPlaneAlt,
  faBallotCheck,
  faFax,
  faBullhorn,
  faBullseyeArrow,
  faGraduationCap,
  falTrain,
  falSubway,
  faStore,
  faTshirt,
  faToothbrush,
  faShower,
  faShoePrints,
  faUtensils,
  faExternalLinkSquareAlt,
  faBoothCurtain,
  faSoup,
  faWarehouseAlt,
  fasFaMapMarkerAlt,
  farExternalLink,
  faLongArrowRight,
  faLongArrowDown
)
Vue.component(FontAwesomeIcon.name, FontAwesomeIcon)
